name = "hsw-api"
main = "src/index.ts"
compatibility_date = "2024-11-21"
workers_dev = true

[dev]
port = 8787

[[d1_databases]]
binding = "DB"        # available at env.DB
database_name = "hsw"
database_id = "6772f704-d89f-4be4-8c08-368d5ddd5797"

[[r2_buckets]]
binding = "R2"        # available at env.R2
bucket_name = "hsw-artifacts"

[vars]
API_RATE_LIMIT_PER_MIN = "60"

[triggers]
crons = ["0 * * * *"] # hourly ETL tick (can be a no-op locally)
